name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Build Android
        run: |
          flutter pub get
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Android
          path: ./build/app/outputs/flutter-apk/app-release.apk
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Build iOS
        run: |
          flutter pub get
          flutter build ios --release --no-codesign
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: iOS
          path: ./build/ios/iphoneos/Runner.app
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Build Web
        run: |
          flutter pub get
          flutter build web --release
      - name: Upload Web
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: ./build/web
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Build Windows
        run: |
          flutter pub get
          flutter build windows --release
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: ./build/windows/runner/Release
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Build Linux
        run: |
          flutter pub get
          flutter build linux --release
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: ./build/linux/x64/release/bundle
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.9.0-0.1.pre"
          channel: "beta"
          cache: true
      - name: Build macOS
        run: |
          flutter pub get
          flutter build macos --release
      - name: Upload macOS
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ./build/macos/Build/Products/Release
